### PR TITLE
Guard against `patch` being `undefined`

### LINKED ISSUE #120: `TypeError` thrown when computing changed files
This action failed on a PR that does not touch the configuration:

Screen Shot 2022-01-07 at 2 43 57 PM

```
Error: TypeError: Cannot read property 'slice' of undefined
Error: Cannot read property 'slice' of undefined
```

Other recent PRs using the same configuration do not have this error. There is only one instance of `slice` in this repo added in #106. Since the `file.patch.slice` comes after a map on `f: any`, this might be addressed by using the return type of `client.paginate` but a cursory search did not reveal what that would be.

### PR DESCRIPTION
**Pull request by mjgpy3**
Resolves #120

### CODE REVIEW

File: src/commenter.ts [hunk 1]
```diff
@@ -53,7 +53,8 @@ async function getChangedFiles(client: ClientType): Promise<ChangedFile[]> {
   const listFilesResponse = await client.paginate(listFilesOptions);
   const changedFiles = listFilesResponse.map((f: any) => ({
```
Comment (stackptr) [inline src/commenter.ts:54]: Does `ClientType` not give any means to type this `f`?

**Review by stackptr — COMMENTED** [review]
Is there any way to type the

**Comment by mjgpy3** [comment]
@stackptr done, good call!

Had to import the types from the underlying library but not too tricky. Looks like my `npm i` also updated a bunch of dependabot PRs we've merged.

File: src/commenter.ts [hunk 2]
```diff
@@ -50,10 +53,11 @@ async function getChangedFiles(client: ClientType): Promise<ChangedFile[]> {
     pull_number: github.context.issue.number,
   });
 
-  const listFilesResponse = await client.paginate(listFilesOptions);
-  const changedFiles = listFilesResponse.map((f: any) => ({
+  const listFilesResponse = await client.paginate<{filename: string, patch?: string}>(listFilesOptions);
```
Comment (stackptr) [inline src/commenter.ts:56]: So the library still requires you to know that `patch?: string`? If you leave that out does it fill out the type to be nullable?

File: src/commenter.ts [hunk 3]
```diff
@@ -50,10 +53,11 @@ async function getChangedFiles(client: ClientType): Promise<ChangedFile[]> {
...
+  const changedFiles = listFilesResponse.map(f => ({
     filename: f.filename,
-    patch: f.patch,
+    // `patch` is `undefined` at times: https://github.com/freckle/commenter-action/issues/120
```
Comment (stackptr) [inline src/commenter.ts:59]: Comment is more relevant above where the type is given to `client.paginate` though ideally it would be unnecessary if the library types stated that `patch` is `undefined` at times.

Comment (mjgpy3) [reply src/commenter.ts:59]: Whoops! Leftover comment, I'll clean it up.

File: src/commenter.ts (hunk 2 above)
Comment (mjgpy3) [reply src/commenter.ts:56]: Sorry, I think I made a blunder here... Looking into it now.

Comment (mjgpy3) [reply src/commenter.ts]: @stackptr not sure what happened there (I must have undone some of my changes locally). See latest commit.

**Review by stackptr — APPROVED** [review]
